name: 'AI IaC Security Auditor'
description: 'Scans a Terraform file or directory for security vulnerabilities.'
author: 'Sabina Bialic'

inputs:
  filepath:
    description: 'The path to the Terraform file or directory to audit.'
    required: true
  github-token:
    description: 'The GITHUB_TOKEN to post PR comments.'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filepath }}
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}

branding:
  icon: 'shield'
  color: 'blue'
