name: Test Published Security Auditor

on:
  workflow_dispatch:
    inputs:
      directory_to_scan:
        description: 'Directory containing Terraform files to audit'
        required: true
        default: 'test'

jobs:
  test-auditor-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        
      - name: Run AI IaC Security Auditor
        uses: sabinabialic/ai-iac-security-auditor@v1.0.1
        with:
          filepath: ${{ github.event.inputs.directory_to_scan }}
        env:
          # This secret must be set in the repository running this workflow
          HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
